//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : IObject.hpp
//  @ Date : 06.08.2020
//  @ Author : 
//
//


#if !defined(_IOBJECT_H)
#define _IOBJECT_H

#include "ObjectDescriptions.hpp"

class IObject {
public:
    virtual void setDescriptionsn(ObjectDescriptions descriptions) = 0;
    virtual ObjectDescriptions getDescriptions() = 0;
};

#endif  //_IOBJECT_H
