//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ObjectDescriptions.hpp
//  @ Date : 06.08.2020
//  @ Author : 
//
//
#if !defined(_OBJECTDESCRIPTIONS_H)
#define _OBJECTDESCRIPTIONS_H

#include <stdint.h>


namespace Description {
    enum EDirection {
        UP = 0,
        DOWN ,
        RIGHT,
        LEFT
    };
}

struct ObjectDescriptions {
    uint8_t mPositionX;
    uint8_t mPositionY;
    uint8_t mSpeed;
    Description::EDirection mDirection;
};

#endif  //_OBJECTDESCRIPTIONS_H
