//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : GamePhysics.cpp
//  @ Date : 06.08.2020
//  @ Author : 
//
//
#include "GamePhysics.hpp"
#include "MicroStopwatch.hpp"

#include <windows.h>
#include <ctime>
#include <iostream>
#include <thread>
#include <chrono>


//------------------------------------------------------------------------------------------
GamePhysics::GamePhysics()
//------------------------------------------------------------------------------------------
{
    mFildArray = new uint8_t*[ySize];
    for(uint8_t a = 0; a < ySize; ++a){
        mFildArray[a] = new uint8_t[xSize];
    }

    for(uint8_t y = 0; y < ySize; ++y){
        for(uint8_t x = 0; x < xSize; ++x){
            mFildArray[y][x] = '_';
        }
    }
}

//------------------------------------------------------------------------------------------
GamePhysics::~GamePhysics()
//------------------------------------------------------------------------------------------
{
    for(int a = 0; a < ySize; ++a){
            delete [] mFildArray[a];
        }
        delete [] mFildArray;
}

//------------------------------------------------------------------------------------------
void GamePhysics::starGameLoop()
//------------------------------------------------------------------------------------------
{
    MicroStopwatch mTimer;
    while (true) {
        mTimer.Start();

        updateObects();
        renderField();

        std::this_thread::sleep_for(std::chrono::milliseconds((1000/30) - mTimer.Now()));
        //std::cout << " time: " << mTimer.Now() << std::endl;

        //system("pause");
    }


}

//------------------------------------------------------------------------------------------
void GamePhysics::addObcet(IObject* obj)
//------------------------------------------------------------------------------------------
{
    if(obj != nullptr){
        mObjectList.push_back(obj);
    }
}

//------------------------------------------------------------------------------------------
void GamePhysics::updateObects()
//------------------------------------------------------------------------------------------
{
    for (auto & object: mObjectList){
        //do something
    }
}

//------------------------------------------------------------------------------------------
void GamePhysics::renderField()
//------------------------------------------------------------------------------------------
{
    for (auto & object: mObjectList){
        mFildArray[object->getDescriptions().mPositionX][object->getDescriptions().mPositionY] = 'x';
    }
    ConsoleOutput::init().print(mFildArray, xSize, ySize);
    //system("pause");
}

